spring.application.name=APIGateway

server.port=8080

app.security.jwt-secret=dev-jwt-secret-please-change-32-bytes-minimum-123456
app.security.public-paths=/auth/ping,/auth/ping/**,/wallet/ping,/wallet/ping/**,/auth/login
app.security.cors.allowed-origins=http://localhost:3000
app.security.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
app.security.cors.allowed-headers=*
app.security.cors.exposed-headers=Authorization

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=wallet-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/wallet/**
