spring.application.name=AuthService

server.port=8081

app.security.jwt-secret=dev-jwt-secret-please-change-32-bytes-minimum-123456
app.security.jwt-expiration-ms=3600000
app.security.public-paths=/auth/ping,/auth/login
app.security.cors.allowed-origins=http://localhost:3000
app.security.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
app.security.cors.allowed-headers=*
app.security.cors.exposed-headers=Authorization

spring.datasource.url=jdbc:mysql://localhost:3306/authsj
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
