spring.application.name=WalletService

server.port=8082

app.security.jwt-secret=dev-jwt-secret-please-change-32-bytes-minimum-123456
app.security.public-paths=/wallet/ping,/wallet/ping/**

spring.datasource.url=jdbc:mysql://localhost:3306/walletsj
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver